### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by ltropin** [epam-cross-platform-lab/swagger-dart-code-generator#190]
Hello, when generating the code, the following error appears:

```
[SEVERE] swagger_dart_code_generator:swagger_dart_code_generator on swagger/api-docs.swagger:

Null check operator used on a null value
```

my **build.yaml**:
```
targets:
  $default:
    sources:
      - lib/**
      - swaggers/**
      - swagger/**
      - $package$
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: 'swagger/'
          output_folder: 'generated/'
          with_base_url: true
          with_converter: true
          use_required_attribute_for_headers: true
          ignore_headers: false
          use_default_null_for_lists: false
          use_inheritance: false
          build_only_models: false
          include_if_null:
            enabled: true
            value: false
```

**packages**:

```
json_annotation: ^4.0.1
build_runner: ^2.0.6
chopper_generator: ^4.0.1
json_serializable: ^4.1.3
swagger_dart_code_generator: ^2.0.7
chopper: ^4.0.1
```
