### ISSUE TITLE
include_if_null does not appear to have an effect

### ISSUE THREAD

**Issue by point-source** [epam-cross-platform-lab/swagger-dart-code-generator#203]
I am generating code from [this swagger file](https://github.com/plaid/plaid-openapi/blob/master/2020-09-14.yml) using the following build options with version 2.0.8+1:

```yaml
targets:
  $default:
    sources:
      - $package$
      - lib/**
    builders:
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          include_if_null:
            enabled: false
          input_folder: "lib/swagger/"
          output_folder: "lib/generated/"
```

Changing the `include_if_null` between true/false does not appear to have an effect on the output. Null values are still being serialized. Specifically, the fields "client_id" and "secret" in the body of every request are being serialized even while null.

The below quote was my original use-case for this but I have since solved it. (in short, plaid will accept both header AND body client_id/secret values though I'm not sure which overrides.) I am leaving this issue open though since we should probably make sure `include_if_null` is working properly anyway.

> This is an issue because the Plaid service allows you to specify client_id and secret in either the header OR the body. Since the generated code includes these fields in every request, my injected header conflicts with the body. My options are:
> 
> 1. **Edit the swagger spec by hand to remove these fields** (but we shouldn't have to manually edit specs) and then inject via header
> 2. **Require the user of the generated library to provide client_id/secret with every request** (but this is bad UX)
> 3. **Inject the client_id/secret into each request body via a chopper converter** (but since requests are strongly typed, immutable, and do not inherit from a single Request type, we cannot use the copyWith extension method because we can't guarantee it exists on the incoming type. We would have to somehow figure out if the body can be converted to json, convert it, modify, re-encode it, build a new request, pass that along to the next converter which will encode it again. This is inefficient/unreliable)
> 4. **Disable null field serialization/inclusion** (but this is global and could cause issues in cases where we want to set something to null on purpose via API)
> 
> It would be great to have a way to ignore certain request properties and avoid generating them. Or, have every request inherit from a parent so we can do a runtime check to guarantee that that copyWith, toJson, and fromJson methods are available in converters.
> 
> Thoughts?

**Comment by Vovanella95** [comment]
Hi @point-source ,

To use include_if_null feature you need to set it's value.

 include_if_null:
            enabled: true
            value: false


This way you can set includeIfNull: true, false or not use this feature at all. Possible we can optimize it and not use this feature when include_if_null is not defined. But currently it works as it. 

So just set value to true or false and enjoy the result

Let me know if something is not clear.

**Comment by Vovanella95** [comment]
@point-source 

Since 2.1.0-prerelease.3 and in 2.1.0 branch you can use just
includeIfNull: false/true or not to use this flag if you don't want to add this attribute.

**Comment by point-source** [comment]
According to the json_serializable docs, the default value of includeIfNull is true. So for swagger_dart_code_generator, what is the behavioral difference between these settings:

```yaml
include_if_null:
  enabled: false
  value: false
```
```yaml
include_if_null:
  enabled: true
  value: true
```
```yaml
include_if_null:
  enabled: false
  value: true
```

I seem to misunderstand how these switches work because it seems to me that all three of these configs would behave the same. The only one that would seem to change json_serializable's default is this:

```yaml
include_if_null:
  enabled: true
  value: false
```
