### ISSUE TITLE
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type <Type> in type cast

### ISSUE THREAD

**Issue by Dafaque** [epam-cross-platform-lab/swagger-dart-code-generator#219]
Hi!
My config:
```targets:
  $default:
    sources:
      - lib/**
      - swag/**
    builders:
      swagger_dart_code_generator:
        options:
          with_base_url: false
          input_folder: "swag/"
          output_folder: "lib/api/"
          include_path::
            - "swag/*"
          include_if_null:
            enabled: true
            value: false
          with_converter: true
```
Chema contains this part:
```
...
"/rooms": {
    "get": {
        "operationId": "getRooms",
        "parameters": [
            {
                "type": "string",
                "description": "Rooms owner",
                "name": "id",
                "in": "query",
                "required": true
            }
        ],
        "responses": {
            "200": {
                "description": "Loaded rooms",
                "schema": {
                    "type": "array",
                    "items": {
                    "$ref": "#/definitions/room"
                    }
                }
            },
        }
    }
},
...
"definitions":{
    "room": {
        "type": "object",
        "properties": {
            "author": {
                "description": "UUIDv4 of author of last message",
                "type": "string"
            },
            "avatar": {
                "description": "UUIDv4 of fake user as avatar of room",
                "type": "string"
            },
            "id": {
                "description": "UUIDv4 of room",
                "type": "string"
            },
            "lastMessage": {
                "description": "Last message payload",
                "type": "string"
            },
            "name": {
                "description": "Fake user name as room name",
                "type": "string"
            }
        }
    }
}
```

I've generated .dart code with `flutter pub run build_runner build --delete-conflicting-outputs`

Later, i'm trying to execute `getRooms` method. Signature is correct: 
<img width="529" alt="Снимок экрана 2021-08-23 в 18 56 07" src="https://user-images.githubusercontent.com/47787979/130478752-40441f83-e488-4424-8a97-221fcbe1cc33.png">

But any operation with access to `value.body` is failed with unhandled exception.
Error says, that data inside `value.body` is not expected generic `Room`, it's a map.

I'm tracked problem until `Swagger.getRooms -> client.send -> _handleSuccessResponse -> _decodeResponse -> withConverter.converResponse`. There is no call of Room.fromJson or e.t.c., just JSON decoders.
In `_interceptResponse` still no `.fromJson` methods. There is no calls of `.fromJson` in entire `output_folder`:
<img width="761" alt="Снимок экрана 2021-08-23 в 19 04 47" src="https://user-images.githubusercontent.com/47787979/130480212-45a4c38d-47b6-4d57-ba23-e6dc70fc5b04.png">
  

Is it misconfig or misunderstand?

**Comment by Vovanella95** [comment]
Hi @Dafaque ,

Please use just include_if_null: true/false

Since prerelease it's just bool value.

**Comment by Vovanella95** [comment]
@Dafaque 

https://github.com/epam-cross-platform-lab/swagger-dart-code-generator#includeIfNull-for-model-generation
See note. NOTE! FOR 2.1.0 and higher use just include_if_null: true/false

I will remove this note and update description to avoid misunderstandings..

**Comment by Dafaque** [comment]
Hi!
Changed as you told. Now got this err while generating:
```
type 'bool' is not a subtype of type 'Map<dynamic, dynamic>' in type cast
pub finished with exit code 78
```
Config now:
```
targets:
  $default:
    sources:
      - lib/**
      - swag/**
    builders:
      swagger_dart_code_generator:
        options:
          with_base_url: false
          input_folder: "swag/"
          output_folder: "lib/api/"
          include_path::
            - "swag/*"
          include_if_null: true
          with_converter: true
```
Using latest ver:
```
# pubspec.lock
swagger_dart_code_generator:
    dependency: "direct dev"
    description:
      name: swagger_dart_code_generator
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.8+1"
```

**Comment by Dafaque** [comment]
Hi!
Upgraded to `2.1.0-prerelease.6`., and changed as you told.
Now error while try to generate files:
```
[SEVERE] 
type 'bool' is not a subtype of type 'Map<dynamic, dynamic>' in type cast
```
If use previous version will throw this error:
```
[SEVERE] 
type 'YamlMap' is not a subtype of type 'bool?' in type cast
pub finished with exit code 78
```

And if not use this key at all error won't appear.
But topic issue still appear.

**Comment by Vovanella95** [comment]
@Dafaque , please make flutter clean and flutter pub get. It could help

**Comment by Vovanella95** [comment]
@Dafaque if issue still appear - please share build.yaml file

**Comment by Dafaque** [comment]
`clean` helped with generation, but issue still here:
<img width="954" alt="Снимок экрана 2021-08-24 в 12 51 42" src="https://user-images.githubusercontent.com/47787979/130596950-002e94ad-1ea3-4046-8c9b-c37b5d30ce39.png">

__build.yaml__:
```
targets:
  $default:
    sources:
      - lib/**
      - swag/**
    builders:
      swagger_dart_code_generator:
        options:
          with_base_url: false
          input_folder: "swag/"
          output_folder: "lib/api/"
          include_path::
            - "swag/*"
          with_converter: true
          include_if_null: true
```
