### ISSUE TITLE
[BUG] No request body types are generated

### ISSUE THREAD

**Issue by masseelch** [epam-cross-platform-lab/swagger-dart-code-generator#265]
**Describe the bug**
No `BodyType`s are generated or of the `requestBody. `Object` is used on every `POST` / `PATCH`.

**To Reproduce**
Use [this openapi.json](https://github.com/masseelch/elk/blob/a1191f864b40829c114bc3728f53f0686fb0f909/internal/fridge/ent/openapi.json) and run the generator.

**Expected behavior**
The spec defines a `requestBody`. The generated code creates a type for the body.

**Library version used:**
```yaml
dependencies:
  flutter:
    sdk: flutter
  chopper: ^4.0.1
  flutter_svg: ^0.23.0+1
  json_annotation: ^4.3.0
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  vrouter: ^1.2.0+14
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  swagger_dart_code_generator: ^2.1.3+1
  chopper_generator: ^4.0.2
  build_runner: ^2.1.2
  json_serializable: ^6.0.0
```

**Additional context**
Example of the generated Code.
```dart
@override
  Future<Response<DisplayCreateView>> displaysPost(
      {required Object? body}) {
    final $url = '/displays';
    final $body = body;
    final $request = Request('POST', $url, client.baseUrl, body: $body);
    return client.send<DisplayCreateView, DisplayCreateView>($request);
  }
```
