### ISSUE TITLE
[BUG] Patch routes are not generated.

### ISSUE THREAD

**Issue by masseelch** [epam-cross-platform-lab/swagger-dart-code-generator#266]
**Describe the bug**
When the spec contains a route with PATCH verb no route is generated.

**To Reproduce**
Take [this file](https://github.com/masseelch/elk/blob/a1191f864b40829c114bc3728f53f0686fb0f909/internal/fridge/ent/openapi.json) and generate the code. Patch routes are missing.

**Expected behavior**
Patch routes are generated.

**Library version used:**
```yaml
dependencies:
  flutter:
    sdk: flutter
  chopper: ^4.0.1
  flutter_svg: ^0.23.0+1
  json_annotation: ^4.3.0
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  vrouter: ^1.2.0+14
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  swagger_dart_code_generator: ^2.1.3+1
  chopper_generator: ^4.0.2
  build_runner: ^2.1.2
  json_serializable: ^6.0.0

```
