### ISSUE TITLE
"You have hit a bug in build runner"

### ISSUE THREAD

**Issue by RoarGronmo** [epam-cross-platform-lab/swagger-dart-code-generator#277]
**Describe the bug**
ran: `flutter pub run build_runner --delete-conflicting-outputs`

with swagger contents in 
`c:\flutterprojects\m_work_sandbox_4_2\swaggers\m_work_api.swagger`

with following configs (see pubspec.yaml.txt):
[pubspec.yaml.txt](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/files/7531670/pubspec.yaml.txt)

and following swagger file( see m_work_api.swagger.txt):
[m_work_api.swagger.txt](https://github.com/epam-cross-platform-lab/swagger-dart-code-generator/files/7531687/m_work_api.swagger.txt)

Note: the files above has .txt types because github won't allow .yaml and .swagger files to be uploaded.

generates following message in powershell: 

```
PS C:\flutterprojects\m_work_sandbox_4_2> flutter pub run build_runner build --delete-conflicting-outputs
[INFO] Generating build script...
[INFO] Generating build script completed, took 401ms

[INFO] Precompiling build script......
[INFO] Precompiling build script... completed, took 6.1s



You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


Bad state: No element
dart:core                                                                   Iterable.first
package:swagger_dart_code_generator/swagger_dart_code_generator.dart 46:27  _generateExtensions
package:swagger_dart_code_generator/swagger_dart_code_generator.dart 60:32  SwaggerDartCodeGenerator.buildExtensions
package:build_runner_core/src/package_graph/apply_builders.dart 403:33      _validateBuilder
package:build_runner_core/src/package_graph/apply_builders.dart 183:9       new BuilderApplication.forBuilder.<fn>.<fn>
package:build_runner_core/src/package_graph/apply_builders.dart 346:27      _createBuildPhasesForBuilderInCycle.<fn>.<fn>
dart:core                                                                   Iterable.toList
package:build_runner_core/src/package_graph/apply_builders.dart 293:8       createBuildPhases
package:build_runner_core/src/generate/build_impl.dart 109:29               BuildImpl.create
package:build_runner_core/src/generate/build_runner.dart 34:42              BuildRunner.create
package:build_runner/src/generate/build.dart 109:35                         build
package:build_runner/src/entrypoint/build.dart 35:18                        BuildCommand._run
package:args/command_runner.dart 209:13                                     CommandRunner.runCommand
package:build_runner/src/entrypoint/run.dart 26:18                          run
.dart_tool\build\entrypoint\build.dart 31:16                                main

pub finished with exit code 1
```

**Expected behavior**

I expected files to be created

**Library version used:**

extract from pubspec.yaml
```
dependencies:
...
   json_annotation: ^4.3.0
  chopper: ^4.0.3
...
dev-dependencies:
...
  build_runner: ^2.1.2
  chopper_generator: ^4.0.3
  swagger_dart_code_generator: any
...

targets:
  $default:
    sources:
      - swaggers/**
      - lib/**
    builders:
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "lib/"
          output_folder: "lib/swagger_generated_code"
```

**Additional context**
Since the errormessage says I should file an error at dart-lang there, is it more likely that error resides here.

**Comment by JanSteffes** [comment]
I've hit the same error. i got one more line that at least describes the error a little more:

```
PS H:\Dateien\Entwicklung\Git\Repositories\scan_server_api> flutter pub run build_runner build --delete-conflicting-outputs
[INFO] Generating build script...
[INFO] Generating build script completed, took 519ms

[INFO] Precompiling build script......
[INFO] Precompiling build script... completed, took 7.7s

[WARNING] The package `scan_server_api` does not include some required sources in any of its targets (see their build.yaml file).
The missing sources are:
  - $package$


You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


Bad state: No element
dart:core                                                                   Iterable.first
package:swagger_dart_code_generator/swagger_dart_code_generator.dart 46:27  _generateExtensions
package:swagger_dart_code_generator/swagger_dart_code_generator.dart 60:32  SwaggerDartCodeGenerator.buildExtensions
package:build_runner_core/src/package_graph/apply_builders.dart 403:33      _validateBuilder
package:build_runner_core/src/package_graph/apply_builders.dart 183:9       new BuilderApplication.forBuilder.<fn>.<fn>
package:build_runner_core/src/package_graph/apply_builders.dart 346:27      _createBuildPhasesForBuilderInCycle.<fn>.<fn>
dart:core                                                                   Iterable.toList
package:build_runner_core/src/package_graph/apply_builders.dart 293:8       createBuildPhases
package:build_runner_core/src/generate/build_impl.dart 109:29               BuildImpl.create
package:build_runner_core/src/generate/build_runner.dart 34:42              BuildRunner.create
package:build_runner/src/generate/build.dart 109:35                         build
package:build_runner/src/entrypoint/build.dart 35:18                        BuildCommand._run
package:args/command_runner.dart 209:13                                     CommandRunner.runCommand
package:build_runner/src/entrypoint/run.dart 26:18                          run
.dart_tool\build\entrypoint\build.dart 31:16                                main

pub finished with exit code 1
```

with build.yaml:
```
targets:
  $default:
    sources:     
      - swaggers/**
      - lib/**
    builders:
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "lib/"
          output_folder: "lib/swagger_generated_code/"

```

I've found nothing regarding $package$ for the build.yaml :\
