### ISSUE TITLE
[FEATURE] Allow specify SWAGGER spec's file from url, to support local development

### ISSUE THREAD

**Issue by fncap** [epam-cross-platform-lab/swagger-dart-code-generator#316]
Actually, the generator accepts a folder within it searches for all swagger specs files.
This behavior fits very well for a 3rdy party WebAPI.
In the scenario, where the WebAPI layer is parallel developed with the app, it could be annoying to copy/paste our swagger file to that folder!
Instead, should be a big improvement if the generator could download it from an URL! 

Please take a look at the following `build.yaml` part:
```yaml
      swagger_dart_code_generator:
        options:
          #instead of this -> input_folder: "swaggers/"
          input_urls: 
           - https://localhost:9001/module1/swagger.json
           - https://localhost:9001/module2/swagger.json
           - https://petstore.swagger.io/v2/swagger.json
          output_folder: "lib/swagger_generated_code/"
```

*NOTE*
It should be helpful if URLs will be managed for local SSL cert, avoiding annoying problem about `INVALID_SSL_CERT`

Thanks for your time!
