### ISSUE TITLE
[BUG] Code generation is failing with "Bad state: no element"

### ISSUE THREAD

**Issue by point-source** [epam-cross-platform-lab/swagger-dart-code-generator#356]
**Describe the bug**
Build fails with:

> Building package executable... (3.4s)
> Built build_runner:build_runner.
> [INFO] Generating build script completed, took 205ms
> [WARNING] Throwing away cached asset graph because the language version of some package(s) changed. This would most commonly happen when updating dependencies or changing your min sdk constraint.
> [INFO] Cleaning up outputs from previous builds. completed, took 6ms
> [INFO] Generating build script completed, took 41ms
> [WARNING] Invalidated precompiled build script due to missing asset graph.
> [INFO] Precompiling build script... completed, took 3.1s
> [INFO] Building new asset graph completed, took 373ms
> [INFO] Checking for unexpected pre-existing outputs. completed, took 0ms
> [SEVERE] swagger_dart_code_generator:swagger_dart_code_generator on swagger/home.swagger:
> 
> Bad state: No element
> [INFO] Generating SDK summary completed, took 1.4s
> [INFO] Running build completed, took 2.1s
> [INFO] Caching finalized dependency graph completed, took 17ms
> [SEVERE] Failed after 2.1s

**To Reproduce**
Try to generate code from this swagger file: https://gist.github.com/point-source/c0ee7e9f271411d44c734c89e879c02c

**Expected behavior**
Code is generated successfully

**Swagger specification link**
https://gist.github.com/point-source/c0ee7e9f271411d44c734c89e879c02c

**Library version used:**
2.4.3

**Additional context:**
Here is my build.yaml:

```yaml
targets:
  $default:
    sources:
      - $package$
      - lib/**
      - swagger/**
    builders:
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          with_base_url: false
          include_if_null: false
          input_folder: "swagger/"
          output_folder: "lib/generated_code/"
```
