### ISSUE TITLE
[BUG] `client_index.dart` in same directory as other generated files

### ISSUE THREAD

**Issue by josxha** [epam-cross-platform-lab/swagger-dart-code-generator#376]
**Describe the bug**
I am trying to use the generator as a package for my project and have seen that `client_index.dart` is generated in the same directory as the other files. 

In the package I use `output_folder: "lib/src"` to generate the files under `/lib/src`, because not all files from my main project have to be visible. However, if `client_index.dart` is now generated in the same directory, I cannot access this file either.

**To Reproduce**
```yaml
swagger_dart_code_generator:
        options:
          input_folder: "input_folder/"
          output_folder: "lib/src"
          [...]
```

**Current file structure**
- lib/
    - src/
        - client_index.dart
        - client_mapping.dart
        - openapi.enums.swagger.dart
        - openap.swagger.chopper.dart
        - openapi.swagger.dart
        - openapi.swagger.g.dart
    

**Required file structure**
- lib/
    - client_index.dart
    - src/
        - client_mapping.dart
        - openapi.enums.swagger.dart
        - openap.swagger.chopper.dart
        - openapi.swagger.dart
        - openapi.swagger.g.dart

**Library version used:**
2.4.8

**Additional context**
Es könnte eine zusätzliche Option `output_folder_index` geben, die den Ort von `client_index.dart` bestimmt.
