### ISSUE TITLE
[BUG] missing export of `.models.swagger.dart` inside `client_index.dart`

### ISSUE THREAD

**Issue by josxha** [epam-cross-platform-lab/swagger-dart-code-generator#377]
**Describe the bug**
If `separate_models: true` is set, `*.models.swagger.dart` should be added to the `client_index.dart` file.

**To Reproduce**
```yaml
swagger_dart_code_generator:
        options:
          separate_models: true
          [...]
```

**Expected content of `client_index.dart`**
```dart
export 'openapi.swagger.dart' show Openapi;
```

**Current content of `client_index.dart`**
```dart
export 'openapi.swagger.dart' show Openapi;
export 'openapi.models.swagger.dart';
```

**Library version used:**
2.4.8
