### ISSUE TITLE
[BUG] Missing some class/enum definitions

### ISSUE THREAD

**Issue by point-source** [epam-cross-platform-lab/swagger-dart-code-generator#458]
**Describe the bug**
When generating an sdk using [this swagger file](https://gist.github.com/point-source/f2b45af0f84a57ee1b39ccc11730ccc7), some classes or enums such as these do not get created:

- ScreensScreenIdGet$RequestBody
- enums.ScreensScreenIdLayersLayerIdPresetsTargetGetTarget
- emums.ScreensScreenIdLayersLayerIdPresetsTargetSourcePostTarget

There are more that are missing but these are an example.

**To Reproduce**
Use this swagger file: https://gist.github.com/point-source/f2b45af0f84a57ee1b39ccc11730ccc7
Use these build.yaml options:
```
targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "lib/swaggers"
          output_folder: "lib/generated/"
          separate_models: true
```

**Expected behavior**
A fully functioning library should be generated without compile errors

**Swagger specification link**
[Link to swagger/OpenApi documentation](https://gist.github.com/point-source/f2b45af0f84a57ee1b39ccc11730ccc7)

**Library version used:**
Dart: 2.17.7
swagger codegen: 2.7.6+1
