### ISSUE TITLE
[BUG] Duplicated enums/maps and invalid convertResponse

### ISSUE THREAD

**Issue by point-source** [epam-cross-platform-lab/swagger-dart-code-generator#469]
**Describe the bug**
When generating an sdk using [this swagger file](https://gist.github.com/point-source/f2b45af0f84a57ee1b39ccc11730ccc7), some map or enums such as these are duplicated:

- enum Target
- const $TargetMap

![Screen Shot 2022-09-20 at 10 36 30 AM](https://user-images.githubusercontent.com/47544779/191326315-66a5fb53-22c7-4688-95ba-b0bd00336a11.png)

Additionally, the generated json converter's `convertResponse` method is not a valid override if the original.
![Screen Shot 2022-09-20 at 10 37 39 AM](https://user-images.githubusercontent.com/47544779/191326571-30099572-b087-4691-8e9f-5e4fc272a033.png)

**To Reproduce**
Use this swagger file: https://gist.github.com/point-source/f2b45af0f84a57ee1b39ccc11730ccc7
Use these build.yaml options:
```
targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "lib/swaggers"
          output_folder: "lib/generated/"
          separate_models: true
```

**Expected behavior**
A fully functioning library should be generated without compile errors

**Swagger specification link**
[Link to swagger/OpenApi documentation](https://gist.github.com/point-source/f2b45af0f84a57ee1b39ccc11730ccc7)

**Library version used:**
Dart: 2.17.6
swagger codegen: 2.8.1

Note, this is the same swagger and setting as issue #458 so I would expect tests to be failing on that ticket too.
