### ISSUE TITLE
[BUG] Expected an identifier with openapi 3.0.3

### ISSUE THREAD

**Issue by mfrischbutter** [epam-cross-platform-lab/swagger-dart-code-generator#484]
**Describe the bug**
We have switched from openapi 2.0 to 3.0.3 and unfortunately we are currently experiencing this error at several points.
I have been able to reduce the Swagger file to this request and reproduce the error.
It is probably related to the type "allOf".

The Swagger file has no syntax errors in the validator.

**Screenshot of the error**
![Bildschirm­foto 2022-11-07 um 16 29 51](https://user-images.githubusercontent.com/33195197/200349346-de99a830-daf4-4fed-af98-87aa2aba58e8.png)

**To Reproduce**
swagger.json
```json
{
  "openapi": "3.0.3",
  "info": {
    "title": "DEV",
    "version": "0.13.0",
    "description": ""
  },
  "paths": {
    "/api/me/": {
      "patch": {
        "operationId": "me_patch",
        "description": "Test",
        "tags": [
          "user"
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/PatchedUserPatch"
              }
            }
          }
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "integer"
                }
              }
            },
            "description": ""
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "PatchedUserPatch": {
        "type": "object",
        "description": "Serializer class for User",
        "properties": {
          "summaries": {
            "allOf": [],
            "description": "Summaries"
          }
        }
      }
    }
  }
}
```

build.yaml
```yaml
targets:
  $default:
    sources:
      - lib/**
      - swaggers/**
      - swaggers2/**
      - input_folder/**
      - swagger_examples/**
      - $package$
      - pubspec.yaml
    builders:
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "input_folder/"
          output_folder: "lib/swagger_generated_code/"
          build_only_models: false
          enums_case_sensitive: true
          separate_models: true

```

I commited the files in my own fork for testing: 
https://github.com/mfrischbutter/swagger-dart-code-generator/commit/e0e2d7c1d3f7e8b30660108da7ae12496bb887da

To reproduce the error:

1. `cd example/`
2. `rm -rf lib/swagger_generated_code`
3. `flutter pub run build_runner build --delete-conflicting-outputs`

**Library version used:**
2.8.4
