### ISSUE TITLE
[BUG] chopper json serializable converter syntax 

### ISSUE THREAD

**Issue by cmflynn** [epam-cross-platform-lab/swagger-dart-code-generator#501]
**Describe the bug**
after generating models and chopper client there is a syntax issue in the generated code. the models themselves work fine and I use independent of chopper but I'd like to try and use chopper as well. 

here's the syntax error: 

```
Error: The return type of the method '$JsonSerializableConverter.convertResponse' is 'FutureOr<Response<ResultType>>', which does not match the return type, 'Response<ResultType>', of the overridden method, 'JsonConverter.convertResponse'.
 - 'Response' is from 'package:chopper/src/response.dart' ('/opt/homebrew/Caskroom/flutter/3.3.2/flutter/.pub-cache/hosted/pub.dartlang.org/chopper-4.0.6/lib/src/response.dart').
Change to a subtype of 'Response<ResultType>'.
  FutureOr<chopper.Response<ResultType>> convertResponse<ResultType, Item>(
                                         ^
/opt/homebrew/Caskroom/flutter/3.3.2/flutter/.pub-cache/hosted/pub.dartlang.org/chopper-4.0.6/lib/src/interceptor.dart:278:22: Context: This is the overridden method ('convertResponse').
  Response<BodyType> convertResponse<BodyType, InnerType>(Response response) {
```

**To Reproduce**
```dart
class $JsonSerializableConverter extends chopper.JsonConverter {
  @override
  FutureOr<chopper.Response<ResultType>> convertResponse<ResultType, Item>(
      chopper.Response response) async {
    if (response.bodyString.isEmpty) {
      // In rare cases, when let's say 204 (no content) is returned -
      // we cannot decode the missing json with the result type specified
      return chopper.Response(response.base, null, error: response.error);
    }

    final jsonRes = await super.convertResponse(response);
    return jsonRes.copyWith<ResultType>(
        body: $jsonDecoder.decode<Item>(jsonRes.body) as ResultType);
  }
}

final $jsonDecoder = $CustomJsonDecoder(generatedMapping);

```

**Library version used:**
```
flutter --version
Flutter 3.3.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e3c29ec00c (9 weeks ago) • 2022-09-14 08:46:55 -0500
Engine • revision a4ff2c53d8
Tools • Dart 2.18.1 • DevTools 2.15.0
```

```
environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  intl: 0.17.0
  provider: 6.0.3
  requests: 4.5.0
  http: 0.13.5
  google_fonts: 3.0.1
  rxdart: 0.27.5
  json_annotation: 4.7.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_form_builder: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.3.2
  build_runner: ^2.1.7
  chopper_generator: ^4.0.5
  json_serializable: ^6.1.4
  swagger_dart_code_generator: ^2.4.6
```
