### ISSUE TITLE
[BUG] The getter fromJsonFactory isn't defined

### ISSUE THREAD

**Issue by Flajt** [epam-cross-platform-lab/swagger-dart-code-generator#554]
**Describe the bug**
`The getter 'fromJsonFactory' isn't defined for the type 'List'.
Try importing the library that defines 'fromJsonFactory', correcting the name to the name of an existing getter, or defining a getter or field named 'fromJsonFactory'.`

**To Reproduce**
Openapi file: [Link](https://github.com/sonallux/spotify-web-api/blob/main/fixed-spotify-open-api.yml) (To large to include here)
Build file: 
```
targets:
  $default:
    sources:     
      include:
      - lib/**
      - $package$
      - lib/openapi/**
      exclude:
        - /lib/openapi/README.txt
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "lib/openapi/"
          output_folder: "lib/logic/generated/"
          with_base_url: true
          with_converter: true
    
```

**Expected behavior**
`toJsonFactory` shouldn't be missing.

**Library version used:**
Latest

**Additional context**
I got this 8 times in the file, I think one error is for a different file.
Maybe it's an issue with the openapi file? 
I also have no return types for the functions related to this only object, idk if that matters.
