### ISSUE TITLE
[BUG] build_runner throws FileSystemException

### ISSUE THREAD

**Issue by gogolon** [epam-cross-platform-lab/swagger-dart-code-generator#567]
**Describe the bug**
Since upgrading from `2.0.0-nullsafety.7+2` to `2.4.7` I've been unable to run the build runner without first deleting all files generated by this package.  
After running 
`flutter pub run build_runner build --delete-conflicting-outputs`
I get an error:
```
You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


FileSystemException: Cannot create file, path = 'lib/data/rest/generated_contracts' (OS Error: Is a directory, errno = 21)
dart:io                                                                     _File.createSync
package:swagger_dart_code_generator/swagger_dart_code_generator.dart 61:30  _generateExtensions
package:swagger_dart_code_generator/swagger_dart_code_generator.dart 99:32  SwaggerDartCodeGenerator.buildExtensions
package:build_runner_core/src/package_graph/apply_builders.dart 403:33      _validateBuilder
package:build_runner_core/src/package_graph/apply_builders.dart 183:9       new BuilderApplication.forBuilder.<fn>.<fn>
package:build_runner_core/src/package_graph/apply_builders.dart 346:27      _createBuildPhasesForBuilderInCycle.<fn>.<fn>
dart:core                                                                   Iterable.toList
package:build_runner_core/src/package_graph/apply_builders.dart 293:8       createBuildPhases
package:build_runner_core/src/generate/build_impl.dart 109:29               BuildImpl.create
package:build_runner_core/src/generate/build_runner.dart 34:42              BuildRunner.create
package:build_runner/src/generate/build.dart 109:35                         build
package:build_runner/src/entrypoint/build.dart 35:18                        BuildCommand._run
package:args/command_runner.dart 196:13                                     CommandRunner.runCommand
package:build_runner/src/entrypoint/run.dart 26:18                          run
.dart_tool/build/entrypoint/build.dart 35:16                                main
```

**Additional context**
My `build.yaml` file looks like this:
```
targets:
  $default:
    sources:
      - lib/**
      - $package$
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: 'lib/data/rest/'
          output_folder: 'lib/data/rest/generated_contracts/'
          with_base_url: true
          use_path_for_request_names: false
      chopper_generator:
        options:
          header: ''
```

**Workaround**
If I remove the `lib/data/rest/generated_contracts/` directory and re-run the build runner, it works.

Is this something that has been already fixed in newer versions? I'd rather stay at 2.4.7, but would like to know if you are aware of this issue.
