### ISSUE TITLE
The argument type 'String' can't be assigned to the parameter type 'Object?'

### ISSUE THREAD

**Issue by 3M35** [epam-cross-platform-lab/swagger-dart-code-generator#585]
After migrating from version 2.2.3 to 2.10.4 generated dart files contain errors regarding enum-types. Please see details below (Error at the bottom). Why is this happening? Any help appreciated :-)

Output flutter doctor:

> [√] Flutter (Channel stable, 3.7.11, on Microsoft Windows [Version 10.0.22621.1413], locale de-DE)
>     • Flutter version 3.7.11 on channel stable at C:\Entwicklung\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision f72efea43c (6 days ago), 2023-04-11 11:57:21 -0700
>     • Engine revision 1a65d409c7
>     • Dart version 2.19.6
>     • DevTools version 2.20.1
> 
> [X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
>     • Android SDK at C:\Users\...\AppData\Local\Android\sdk
>     • Platform android-33, build-tools 31.0.0
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
> 
> [√] Android Studio (version 2022.1)
>     • Android Studio at C:\Program Files\Android\Android Studio1
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)
> 
> [√] VS Code (version 1.77.3)
>     • VS Code at C:\Users\...\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.62.0
> 
> [√] Connected device (4 available)
>     • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
>     • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.22621.1413]
>     • Chrome (web)            • chrome        • web-javascript • Google Chrome 111.0.5563.149
>     • Edge (web)              • edge          • web-javascript • Microsoft Edge 111.0.1661.44
> 
> [√] HTTP Host Availability
>     • All required HTTP hosts are available

build.yaml:
```yaml
targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          build_only_models: true
          input_folder: "lib/swagger/"
          output_folder: "lib/generated/"
    sources:
      - $package$
      - lib/**
 ```
  
pubspec.yaml
```yaml
dependencies:
  …
  json_annotation: 4.8.0
  …

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.3.3 
  json_serializable: 6.6.1

  flutter_lints: 2.0.1 
  flutter_launcher_icons: 0.13.0 

  swagger_dart_code_generator: 2.10.4
```

swagger.json
```json
"Currency":{
   "type":"string",
   "enum":[
      "EUR",
      "USD"
   ]
}
```

swagger.swagger.dart

```dart
String? currencyToJson(enums.Currency? currency) {
  return currency?.value;
}

enums.Currency currencyFromJson(
  Object? currency, [
  enums.Currency? defaultValue,
]) {
  return enums.Currency.values.firstWhereOrNull((e) => e.value == currency) ??
      defaultValue ??
      enums.Currency.swaggerGeneratedUnknown;
}

List<String> currencyListToJson(List<enums.Currency>? currency) {
  if (currency == null) {
    return [];
  }

  return currency.map((e) => e.value!).toList();
}

List<enums.Currency> currencyListFromJson(
  List? currency, [
  List<enums.Currency>? defaultValue,
]) {
  if (currency == null) {
    return defaultValue ?? [];
  }

  return currency.map((e) => currencyFromJson(e.toString())).toList();
}

List<enums.Currency>? currencyNullableListFromJson(
  List? currency, [
  List<enums.Currency>? defaultValue,
]) {
  if (currency == null) {
    return defaultValue;
  }

  return currency.map((e) => currencyFromJson(e.toString())).toList();
}
```

```
lib/generated/swagger.swagger.dart:5316:49: Error: The argument type 'String' can't be assigned to the parameter type 'Object?'.
- 'Object' is from 'package:.../generated/swagger.swagger.dart' ('lib/generated/swagger.swagger.dart').
  return currency.map((e) => currencyFromJson(e.toString())).toList();

```
