### ISSUE TITLE
[BUG] Failure to parse file and generate models from Strapi documentation

### ISSUE THREAD

**Issue by mrares** [epam-cross-platform-lab/swagger-dart-code-generator#590]
**Describe the bug**
I'm trying to generate a client from the Strapi (a popular headless CMS) [full_documentation.json](https://gist.github.com/mrares/262bb696202cbd66a89b191709948b55) (generated by the Strapi documentation plugin)

Initially the generation fails with the following error:
type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast

This is resolved by modifying line 68 ```"items": []``` to ```"items": {}``` (I don't know if this is an issue with the Strapi doc generator or the code generator?)

After generation some errors are found in the .swagger.dart and .swagger.g.dart referring to missing classes.

Strapi version: "4.9.2"
Strapi documentation plugin version: "4.9.2"

##### Flutter dependencies:
```
dependencies:
  flutter:
    sdk: flutter
  auto_route: any
  http: any
  sign_in_with_apple: any
  chopper: ^6.1.1
  json_annotation: ^4.6.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^6.2.0
  build_runner: ^2.1.7
  json_serializable: ^6.0.0
  chopper_generator: ^6.0.0
  swagger_dart_code_generator: ^2.10.4
```

##### Builder config:
```
targets:
  $default:
    sources:
      - lib/**
      - $package$
    builders:
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "./lib/strapi/swagger"
          output_folder: "./lib/strapi/client"
          separate_models: false
          ignore_headers: false
          use_required_attribute_for_headers: false
          include_if_null: true
          with_base_url: false
          with_converter: true
          use_path_for_request_names: true
          use_default_null_for_lists: true
          override_equals_and_hashcode: true
          build_only_models: false
```

**To Reproduce**
Use Strapi and create two content types, with a one-to-many relationship from A to B (such as a Quiz and its Quiz-Questions) in my example.

Use the Strapi Documentation plugin to generate a full_documentation.

Use the builder to generate the dart client.

**Swagger specification link**
[full_documentation.json](https://gist.github.com/mrares/262bb696202cbd66a89b191709948b55) (generated by the Strapi documentation plugin)

**Library version used:**
 ^2.10.4

**Additional context**
