### ISSUE TITLE
Generation fails with 'InvalidType' on Enum

### ISSUE THREAD

**Issue by JaccMirac** [epam-cross-platform-lab/swagger-dart-code-generator#668]
**Describe the bug**
In our Flutter App we try to generate an API-Client for our Backend-API. When trying  run `flutter pub run build_runner build --delete-conflicting-outputs`, it fails with following output on the enum-property 'type' of the model CourseCategoryDto : 
```
[SEVERE] json_serializable on lib/src/generated/api/backend_api.swagger.dart:

Could not generate `fromJson` code for `type`.
To support the type `InvalidType` you can:
* Use `JsonConverter`
  https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonConverter-class.html
* Use `JsonKey` fields `fromJson` and `toJson`
  https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/fromJson.html
  https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonKey/toJson.html
package:memobiotika/src/generated/api/backend_api.swagger.dart:51892:7
      ╷
51892 │       type;
      │       ^^^^
      ╵
```
      
When i get rid of the enum , it passes through the generation process without any errors.

**To Reproduce**
how the schema looks in my backend-api.yaml file:
```
components:
  schemas:
    CourseCategoryDto:
        type: object
        properties:
          id:
            type: string
            format: uuid
          name:
            type: string
          type:
            type: string
            enum:
              - CATEGORY
              - THEME
              - 0
              - 1
            x-enumNames:
              - '0'
              - '1'
              - CATEGORY
              - THEME
        required:
          - id
          - name
          - type

```
**Expected behavior**
Expected behaviour should be that the build_runner runs through the generation process without any errors, or at least fails with a more concrete error-message.

**Library version used:**
swagger_dart_code_generator: 2.11.8
but also fails on latest update:
swagger_dart_code_generator: 2.11.13

If you need any further information please do not hesitate.
