### ISSUE TITLE
[QUESTION] How to make generated code have Auth header?

### ISSUE THREAD

**Issue by RamiroGhilino** [epam-cross-platform-lab/swagger-dart-code-generator#671]
**Please describe a problem.**
I have created some swagger docs for my Django Rest Framework backend using [drf-spectacular](https://drf-spectacular.readthedocs.io/en/latest/) and now i have achieved this: 
```
...
"paths": {
        "/api/academic-units/": {
            "get": {
                "operationId": "academic_units_list",
                "tags": [
                    "academic-units"
                ],
                "security": [
                    {
                        "jwtAuth": []
                    },
                    {}
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/AcademicUnit"
                                    }
                                }
                            }
                        },
                        "description": ""
                    }
                }
            }
            ....
       [some other paths, just pointing i have "security" key]
       ....
       securitySchemes": {
            "jwtAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
        ....
``` 

So now, i'm supposed to send a new Header to this endpoint with the JWT, but generated code in Flutter does not have this parameter. How can i do this? 

My build.yaml:
```
targets:
  $default:
    sources:
      - lib/api/**
    builders:
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "lib/api/"
          output_folder: "lib/swagger_generated_code/"
          ignore_headers: false
```
