### ISSUE TITLE
[QUESTION] Add error line number when parsing yamel 

### ISSUE THREAD

**Issue by guyluz11** [epam-cross-platform-lab/swagger-dart-code-generator#704]
**Please describe a problem.**
Trying to run `dart run build_runner build` but I am getting the error 
> type 'String' is not a subtype of type 'Map<dynamic, dynamic>' in type cast
and I am not sure to what line does it refers.

`build.yaml`
```yaml
targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_urls:
            - "https://raw.githubusercontent.com/Sensibo/sensibo.github.io/master/sensibo.openapi.yaml"
```

**Describe the solution you'd like**
Would be nice if the error message could include the line in the yamel file at which it failed. 

First time using Swagger so I might have just missed something about how to use it, help would be welcomed.
Here is the Swagger editor page 
https://editor.swagger.io/?url=https://raw.githubusercontent.com/Sensibo/sensibo.github.io/master/sensibo.openapi.yaml
