### ISSUE TITLE
[BUG] Generated code does not use security field

### ISSUE THREAD

**Issue by guyluz11** [epam-cross-platform-lab/swagger-dart-code-generator#709]
**Describe the bug**
The generated code does not take into account security field.

**To Reproduce**
1. Download the file as json from the "Swagger specification link".
2. Create a basic build.yaml just to find and generate the file, for example
```
  targets:
    $default:
      builders:
        swagger_dart_code_generator:
          options:
            input_folder: 'src/lib/api'
            output_folder: 'src/lib/api/generated_code/'
```
3. Look at the generated `_usersMePodsGet({` function 

**Expected behavior**
Generated functions are missing `api_key` field as input to authenticate as specified in the `/users/me/pods:` `security:` field.

**Swagger specification link**
[Link to swagger/OpenApi documentation](https://editor.swagger.io/?url=https://raw.githubusercontent.com/Sensibo/sensibo.github.io/master/sensibo.openapi.yaml)

**Library version used:**
  chopper: ^6.1.1
  json_annotation: ^4.8.0

  build_runner: ^2.3.3
  chopper_generator: ^6.0.0
  json_serializable: ^6.6.1
  swagger_dart_code_generator: ^2.10.4

**Additional context**
You can run the code like this
```dart
     Sensibo sensibo = Sensibo.create(baseUrl: apiAddress);
     await sensibo.usersMePodsGet(fields: '*');
```
$request.url in src/api/generated_code/sensibo.swagger.chopper.dart:29 looks like this

`https://home.sensibo.com/api/v2/users/me/pods?fields=*`
and in the "Common Examples" you can see that it should look like this
`https://home.sensibo.com/api/v2/users/me/pods?fields=*&apiKey={api_key}`
