### ISSUE TITLE
[FEATURE] String format type mapping

### ISSUE THREAD

**Issue by Matej-Hlatky** [epam-cross-platform-lab/swagger-dart-code-generator#719]
**Is your feature request related to a problem? Please describe.**

Have option to specify `String` type mapping based on ["format"](https://swagger.io/docs/specification/data-models/data-types/#format) value to custom Dart types, like `uuid`, `Uri`, `Uint8List` etc.

**Describe the solution you'd like**

Be able to specify type mapping via `options` in **build.yaml** file, similar to this:

```yaml
targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          scalars:
            uuid:
              type: uuid
              from_string_function_name: uuidFromString
              to_string_function_name: uuidToString
              import_url: package:uuid/uuid.dart
```

These functions would need to be writen by developer in some specific Dart file.

The inspiration is from [graphql_codegen](https://pub.dev/packages/graphql_codegen#custom-scalars).
