### ISSUE TITLE
[BUG] Error when both overriden_models and separate_models are used

### ISSUE THREAD

**Issue by daniel-deboeverie-lemon** [epam-cross-platform-lab/swagger-dart-code-generator#745]
**Describe the bug**
When separate_models is set to true in the build.yaml whilst overriden_models are defined, the api.models.swagger.dart file gets an import going `import "overriden_models.dart"` that it can not find.

**To Reproduce**
I used the pet_service_json from the example.

and the build.yaml looks as follows:
```
targets:
  $default:
    sources:
      - lib/**
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: lib/swagger
          output_folder: lib/swagger/generated
          separate_models: true
          overriden_models:
            - file_name: "pets"
              import_url: "package:test_project/swagger/overrides/overriden_models.dart"
              overriden_models:
                - "Pet"
  ```

The Pet override class is also just a copy paste form the example.

**Expected behavior**
for the defined import url to be used instead of `import "overriden_models.dart"`

**Library version used:**
2.15.2
