### ISSUE TITLE
[QUESTION] Can I create a custom JsonConverter to support datetime conversion to native methods

### ISSUE THREAD

**Issue by trtiger4520** [epam-cross-platform-lab/swagger-dart-code-generator#750]
I currently save a lot of time using this package on my application.

But I found that I want to use the time field to default to UTC time zone.
Is there a way to make the time convertible to local
Avoid editing automatically generated content or repeatedly manually converting to local time zone

For example, I can write a custom `JsonConverter` method

https://github.com/google/json_serializable.dart/issues/1420#issue-2262511802

**Comment by xioxin** [comment]
I encountered the same need as you, and I noticed that #766 can solve this problem.

Here is the use case for solving this issue:

Upgrade `swagger_dart_code_generator` to `3.0.1`

```yaml
      swagger_dart_code_generator:
        options:
          input_folder: "input_folder/"
          output_folder: "lib/swagger_generated_code/"
          import_paths:
            - "/shared/date_time_converter.dart"
          scalars:
            date-time:
              type: DateTime
              deserialize: parseUtcIsoToLocal
              serialize: toUtcIso8601String
            datetime:
              type: DateTime
              deserialize: parseUtcIsoToLocal
              serialize: toUtcIso8601String
```

/shared/date_time_converter.dart

```dart
DateTime parseUtcIsoToLocal(String utcIso8601String) {
  return DateTime.parse(utcIso8601String).toLocal();
}

String toUtcIso8601String(DateTime dateTime) {
  return dateTime.toUtc().toIso8601String();
}
```
