### ISSUE TITLE
[QUESTION] How to setup multiple swagger 

### ISSUE THREAD

**Issue by GitGud31** [epam-cross-platform-lab/swagger-dart-code-generator#785]
**Problem description.**
I generally have multiple swaggers (multiple services) to work with, but I assume that the package doesn't support multiple input_folders ? Or am I missing something ?

**Solution suggestion**
It's be very handy to have something like the following: 

```
targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          inputs_outputs:
            - input_folder: lib/apis/oauth
            - output_folder: lib/apis/oauth
            - input_folder: lib/apis/file_manager
            - output_folder: lib/apis/file_manager
            - input_folder: lib/apis/global
            - output_folder: lib/apis/global
            - input_folder: lib/apis/referential
            - output_folder: lib/apis/referential
          with_base_url: true
          use_required_attribute_for_headers: true
          with_converter: true
          enums_case_sensitive: true
          separate_models: true
          # cut_from_model_names
```
