### ISSUE TITLE
[BUG] Generator strips dollar signs in request query parameters

### ISSUE THREAD

**Issue by calebdeji** [epam-cross-platform-lab/swagger-dart-code-generator#791]
The generated code for query parameters with dollar ($) doesn't match the initial value. 

**To Reproduce**
``` yaml
  /sub-categories:
    get:
      tags: [Sub-categories]
      summary: List sub-categories
      security:
        - bearerAuth: []
      parameters:
        - name: 'filters[category][id][$eq]'
          in: query
          schema: { type: integer, example: 20 }
          description: Filter by category ID
        - name: 'filters[title][$containsi]'
          in: query
          schema: { type: string, example: 'account' }
          description: Filter by sub-category title
        - name: populate
          in: query
          schema: { type: string, enum: [category] }
          description: Include related category data
        - name: pagination[page]
          in: query
          schema: { type: integer, example: 1 }
          description: Page number
        - name: pagination[pageSize]
          in: query
          schema: { type: integer, example: 25 }
          description: Page size
```

```dart
///List sub-categories
  ///@param filters[category][id][$eq] Filter by category ID
  ///@param filters[title][$containsi] Filter by sub-category title
  ///@param populate Include related category data
  ///@param pagination[page] Page number
  ///@param pagination[pageSize] Page size
  Future<chopper.Response<SubCategoryListResponse>> subCategoriesGet({
    int? filtersCategoryId$eq,
    String? filtersTitle$containsi,
    enums.SubCategoriesGetPopulate? populate,
    int? paginationPage,
    int? paginationPageSize,
  }) {
    generatedMapping.putIfAbsent(SubCategoryListResponse, () => SubCategoryListResponse.fromJsonFactory);

    return _subCategoriesGet(
        filtersCategoryId$eq: filtersCategoryId$eq,
        filtersTitle$containsi: filtersTitle$containsi,
        populate: populate?.value?.toString(),
        paginationPage: paginationPage,
        paginationPageSize: paginationPageSize);
  }

  ///List sub-categories
  ///@param filters[category][id][$eq] Filter by category ID
  ///@param filters[title][$containsi] Filter by sub-category title
  ///@param populate Include related category data
  ///@param pagination[page] Page number
  ///@param pagination[pageSize] Page size
  @Get(path: '/sub-categories')
  Future<chopper.Response<SubCategoryListResponse>> _subCategoriesGet({
    @Query('filters[category][id][eq]') int? filtersCategoryId$eq,
    @Query('filters[title][containsi]') String? filtersTitle$containsi,
    @Query('populate') String? populate,
    @Query('pagination[page]') int? paginationPage,
    @Query('pagination[pageSize]') int? paginationPageSize,
  });
```

The `@Query` annotations' values don't include the dollar sign. 

**Library version used:**
`^3.0.1`
