### ISSUE TITLE
Dependencies update

### ISSUE THREAD

**Issue by gabrielginter** [epam-cross-platform-lab/swagger-dart-code-generator#793]
Would it be possible to get a new version with the updated dependencies?

This package is starting to block other packages from being updated.

**Comment by mamadOuologuem** [comment]
@handgull opened a PR to update dependencies. While it's getting through, you can target its branch in your pubspec.yml like so:

```
  swagger_dart_code_generator:
    git:
      url: git@github.com:handgull/swagger-dart-code-generator.git
      ref: chore/update-dependencies
```
