### ISSUE TITLE
[Support/Bug] build.yml config cannot be found / type 'Null' is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by srad** [epam-cross-platform-lab/swagger-dart-code-generator#798]
**Describe the bug**
Although everything seems setup correctly in my project, the build configuration cannot be found
and generates a null error during build. Hope you can tell me if this is a bug/version issue/oversight by me.

**To Reproduce**

1. Create directories `<root>/swaggers` and `<root>/lib/client`.
2. Copy swagger json into `<root>/swaggers/myclient.json`.
3. Run `flutter pub run build_runner build`.

Output:

```
[INFO] Precompiling build script... completed, took 1.3s
[SEVERE]
type 'Null' is not a subtype of type 'String' in type cast
package:swagger_dart_code_generator/src/models/generator_options.g.dart 39:41  _$GeneratorOptionsFromJson
package:swagger_dart_code_generator/src/models/generator_options.dart 47:7     new GeneratorOptions.fromJson
package:swagger_dart_code_generator/swagger_dart_code_generator.dart 113:32    new SwaggerDartCodeGenerator
package:swagger_dart_code_generator/swagger_dart_code_generator.dart 17:5      swaggerCodeBuilder
package:build_runner                                                           BuildCommand._run
package:args/command_runner.dart 212:13                                        CommandRunner.runCommand
package:build_runner                                                           run
.dart_tool\build\entrypoint\build.dart 63:16                                   main
```

error in line:

```
...
   inputFolder: json['input_folder'] as String,
...
```

The entire build config seems empty.

**Expected behavior**

build.yml be read and client to be generated:

**Swagger specification link**

No even read

**Library version used:**

`pubspec.yml`:

```yml
dependencies:
  flutter:
    sdk: flutter
  chopper: ^8.0.0
  json_annotation: ^4.8.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  chopper_generator: ^8.0.0
  json_serializable: ^6.6.1
  swagger_dart_code_generator: ^3.0.1
```

`<root>/build.yml`:

```yml
targets:
  $default:
    sources:
      - lib/**
      - swaggers/**
      - $package$
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "swaggers"  # Change this to the correct folder
          output_folder: "lib/client/"
```

See above

**Additional context**
