### ISSUE TITLE
[BUG] failed to use scalar option with separate_models

### ISSUE THREAD

**Issue by YochevedShapira** [epam-cross-platform-lab/swagger-dart-code-generator#804]
**Describe the bug**
The code generator incorrectly places the `json_annotation` import with the `as json` alias in the main file instead of the models file where it's needed, causing compilation errors due to undefined json prefix.

**To Reproduce**
add to build file scalar option and set separate_models to true:
build.yaml:
```
targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          scalars:
            date-time:
              type: String
              deserialize: (String json) => json as String
          input_folder: "lib/src/data/data_sources/api/swagger"
          output_folder: "lib/src/data/data_sources/api/swagger/swagger_gen"
          with_base_url: true
          separate_models: true
```

the generated models file is:
```

// Missing import but using json prefix
class _$DateTimeJsonConverter extends json.JsonConverter<DateTime, String> {
  const _$DateTimeJsonConverter();
  // ... rest of the code
}
```

<img width="1029" alt="Image" src="https://github.com/user-attachments/assets/64308ec9-43b7-43be-bd92-0da4db15e0e7" />

I see the import is added to the main file (MyApi.dart file and not MyApi.models.dart file)

**Expected behavior**
The `json_annotation` import with the `as json`alias should be correctly placed in the models file where the json prefix is used, rather than in the main file.

**Library version used:**
3.0.1
